// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package restdeeplinkmodule.actions;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.externalinterface.connector.RequestHandler;
import com.mendix.logging.ILogNode;
import com.mendix.m2ee.api.IMxRuntimeRequest;
import com.mendix.m2ee.api.IMxRuntimeResponse;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IUser;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.ISession;
import java.util.Optional;

public class GetUserFromSession extends CustomJavaAction<IMendixObject>
{
	public GetUserFromSession(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE

		final MyRequestHandler reqHandler = new MyRequestHandler();
		Optional<IMxRuntimeRequest> optRequest = context().getRuntimeRequest();

		if (optRequest.isPresent()){
			ISession session = reqHandler.getSessionFromRequestUnsafe(optRequest.get());

			if (session == null) {
				logger.debug("session is null");
				return null;
			}

			IUser user = session.getUser(context());
			if (user == null) {
				logger.debug("user is null");
				return null;
			}
			logger.debug(String.format("user is %s", user.getName()));
			return user.getMendixObject();

		}

		logger.debug("No request found");
		return null;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetUserFromSession";
	}

	// BEGIN EXTRA CODE
	final ILogNode logger = Core.getLogger("DeepLinkAPI");

	class MyRequestHandler extends RequestHandler {

		public MyRequestHandler() {
			super();
		}

		@Override
		protected void processRequest(IMxRuntimeRequest imrr, IMxRuntimeResponse imrr1, String string) throws Exception {
			throw new UnsupportedOperationException("Not supported yet.");
		}

		public ISession getSessionFromRequestUnsafe(IMxRuntimeRequest request) throws CoreException {
			return this.getSessionFromRequest(request, false); // Don't perform CSRF check - this appears to be the default already
		}

	}

	// END EXTRA CODE
}
