// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package restdeeplinkmodule.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

public class StringFromResource extends CustomJavaAction<java.lang.String>
{
	private java.lang.String FileName;

	public StringFromResource(IContext context, java.lang.String FileName)
	{
		super(context);
		this.FileName = FileName;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuilder sb = new StringBuilder();

		File myFile = new File(Core.getConfiguration().getResourcesPath() +
				File.separator + FileName);

		try(BufferedReader br = new BufferedReader(new FileReader(myFile))) {
			String line;
			while ((line = br.readLine()) != null) {
				sb.append(line);
			}
		} catch (IOException e) {
			return "";
		}

		return sb.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringFromResource";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
